#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "screego"
name = "Screego"
description.en = "Screen sharing for developers"
description.fr = "Partage d'écran pour les développeurs"

version = "1.12.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://screego.net/#/"
demo = "https://app.screego.net/"
admindoc = "https://screego.net/#/"
code = "https://github.com/screego/server"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/screego/server/releases/download/v1.12.3/screego_1.12.3_linux_amd64.tar.gz"
    amd64.sha256 = "5985c4f6da4bc6132a369e8a1f20f309d533e2664a2d89b0b8811928e6600847"
    arm64.url = "https://github.com/screego/server/releases/download/v1.12.3/screego_1.12.3_linux_arm64.tar.gz"
    arm64.sha256 = "e3e183bcd76e78bfc23891fde33bd31ea8c7c368a066adf39fd6a90f7b834e12"
    armhf.url = "https://github.com/screego/server/releases/download/v1.12.3/screego_1.12.3_linux_armv7.tar.gz"
    armhf.sha256 = "7219e1d0658e0fb9ef6e0b980b13ea6db30219bce273098aa6990347d64222b5"
    autoupdate.asset.amd64 = "screego_\\d+\\.\\d+\\.\\d+_linux_amd64\\.tar\\.gz"
    autoupdate.asset.arm64 = "screego_\\d+\\.\\d+\\.\\d+_linux_arm64\\.tar\\.gz"
    autoupdate.asset.armhf = "screego_\\d+\\.\\d+\\.\\d+_linux_armv7\\.tar\\.gz"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5050
    turn.default = 3478
    turn.exposed = "Both"
