#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "john"
    args.password = "0123456"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.340c40a0e19745a1c2c609e8c291b97a616941a6.name = "Upgrade from 1.11.2~ynh1"
