#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --app=$app --key=password --value="$password"

key=$(ynh_string_random)
ynh_app_setting_set --app=$app --key=key --value="$key"

public_ip4="$(curl -s https://ip.yunohost.org/)" || true

#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression "Configuring firewall..."

# Reserve UDP Port range 49152:65535
ynh_hide_warnings yunohost firewall allow UDP -4 49152:65535

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/screego"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="screego.config" --destination="$install_dir/screego.config"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Screen sharing for developers" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# CREAT USER
#=================================================
ynh_script_progression "Creat admin user..."

touch $install_dir/users

chmod 600 "$install_dir/users"
chown $app:$app "$install_dir/users"

($install_dir/screego hash --name "$admin" --pass "$password") >> "$install_dir/users"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
