#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_remove_systemd_config

ynh_remove_nginx_config

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- 49152:65535"
then
    ynh_script_progression --message="Closing UDP ports..." --weight=1
    ynh_exec_warn_less yunohost firewall disallow UDP 49152:65535
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
